# Workflow for building and deploying a React Vite app to GitHub Pages
name: Deploy React Vite App with GitHub Pages

on:
  push:
    branches: ["master"]  # Adjust branch as necessary
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '21.7.1'  # Specify your Node.js version here

      - name: Install dependencies
        run: yarn install

      - name: Build Vite App
        run: yarn build  # Ensure your package.json has a "build" script for Vite

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # Adjust based on your Vite output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
